
version: '3'

services:
  user-service-app:
    container_name: devguild-user-service
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db-user-service
      - mongo-user-service
    ports:
      - 7000:7000
    volumes:
      - .:/home/app:cached
      - ./package.json:/home/app/package.json:cached
    networks: 
      - devguild-user-service-network

  mongo-user-service:
    container_name: devguild-user-service-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=devguild-user-comments
      - MONGO_INITDB_ROOT_PASSWORD=devguild-user-mongodb

  db-user-service:
    image: postgres:9.4
    container_name: devguild-user-service-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=devguild
      - POSTGRES_PASSWORD=user-service
      - POSTGRES_DB=devguild-user-db
    networks:
      - devguild-user-service-network

networks:
  devguild-user-service-network:
    external:
      name: default_services_network